# load env vars
export $(cat ~/workspace/.env | xargs)

# Alias vim to nvim
alias vi='nvim'

# Safe rm
alias rm="rm -i"

# Docker aliases
alias dc='docker compose'
# alias drmin='docker images | tr -s " " | cut -d" " -f 3 | xargs docker rmi'
alias drmin='docker images | grep none | tr -s " " | cut -d" " -f 3 | xargs docker rmi'
alias dimgs='docker images'
alias drma='docker ps -aq | xargs docker rm -f'
alias docker_runit='docker run -it --rm $@'
alias docker_runit_here='docker run -v $(PWD):/app -w /app -it --rm $@'
alias dpsa='docker ps -a'
alias dcrs='docker compose run --service-ports --use-aliases'

# Vagrant aliases
alias v='vagrant'
alias vh='vagrant halt'
alias vs='vagrant up && vagrant ssh'
alias vst='vagrant up && vagrant ssh -c "tmux -CC"'

alias l='ls -lhaG'

#git
alias g='git'
alias gc='git commit'
alias gs='git status'
alias gco='git checkout'
alias gap='git add -p'
alias gsl='git stash list'
alias gaa='git add .; git commit --amend --no-edit'

# Up 'n' folders
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# Grep with color
alias grep='grep --color=auto '

# Find all cyr symbols
alias cyr='grep "[А-я,Ё,ё]" '

# Show all files extensions
alias lfe="find . -type f | sed -En 's|.*/[^/]+\.([^/.]+)$|\1|p' | sort -u"

alias pbcopy='xsel --clipboard --input'

alias enw='emacs -nw'
alias se='eval `ssh-agent`'

## History configuration
# Appending history instead of rewriting
shopt -s histappend

# Ignore duplicates while appending and erase duplicates from old history
HISTCONTROL=ignoredups:erasedups

# Ignore aliases and some other patterns when write history
HISTIGNORE="$(alias | cut -d' ' -f2 | cut -d'=' -f1 | tr '\n' ':')[bf]g:exit:pwd:ls:cd:vi"

# Show unstaged (*) and staged (+) changes next to the branch name.
GIT_PS1_SHOWDIRTYSTATE=1
# If something is stashed, then a '$' will be shown next to the branch name.
GIT_PS1_SHOWSTASHSTATE=1
# If there're untracked files, then a '%' will be shown next to the branch name.
GIT_PS1_SHOWUNTRACKEDFILES=1
# Show the difference between HEAD and its upstream with number of commits ahead/behind (+/-) upstream
GIT_PS1_SHOWUPSTREAM="auto verbose"

alias __git_ps1="git branch 2>/dev/null | grep '*' | sed 's/* \(.*\)/(\1)/'"

set_prompt () {
    orange='\[\033[0;33m\]'
    reset='\[\e[00m\]'
    PS1="$(__git_ps1) \A $orange\W\$$reset "
}
PROMPT_COMMAND=set_prompt

export VISUAL="vim"
export PATH=$HOME/bin:$PATH
export PATH="/home/azx/Projects:${PATH}"

export PATH=$HOME.local/bin:$PATH

export PATH=~/.npm-global/bin:$PATH

export GEM_HOME="$HOME/.gems"
export GEM_PATH="$GEM_HOME:/var/lib/ruby/gems/3.0"


export PATH=/usr/local/bin/rvm/bin:$PATH

export PATH=$GEM_HOME/bin:$PATH

export FLYCTL_INSTALL="/home/azx/.fly"
export PATH="$FLYCTL_INSTALL/bin:$PATH"

export PATH=~/.fly/bin:$PATH
export KUBECONFIG=$HOME/.kube/config


export PATH=/home/azx/.gems/bin:$PATH

export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

export TERM=xterm-256color

# export PATH=/usr/local/bin/rvm/gems/ruby-3.1.2:$PATH
# export RVM_PATH=/home/azx/.rvm
# export RVM_PATH=/home/azx/.rvm

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# asdf
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

alias mu="sudo chown -R azx:azx ."

# https://github.com/mikenye/docker-youtube-dl
alias yt-dl='docker run \
                  --rm -i \
                  -e PGID=$(id -g) \
                  -e PUID=$(id -u) \
                  -v "$(pwd)":/workdir:rw \
                  ghcr.io/mikenye/docker-youtube-dl:latest'
