---

- hosts: local
  roles:
    - role: dotfiles
    - role: geerlingguy.docker
      become: true
    - role: cimon-io.asdf
      asdf_user: azx
      asdf_group: azx
      asdf_plugins:
      - name: "ruby"
        versions: ["3.0.0"]
        global: "3.0.0"
      - name: "golang"
        versions: ["1.20.5"]
        global: "1.20.5"
      - name: "nodejs"
        versions: ["20.2.0"]
        global: "20.2.0"
    - role: packages
    - role: emacs
      become: true
