---

- hosts: remote
  tags: remote
  roles:
    - role: dotfiles
    - role: geerlingguy.docker
    - role: cimon-io.asdf
      asdf_user: root
      asdf_group: root
      asdf_plugins:
      - name: "ruby"
        versions: ["3.0.0"]
        global: "3.0.0"
    - role: packages
    - role: emacs
