- name: Install software-properties-common
  become: true
  apt:
    pkg:
      - software-properties-common

- name: Install packages
  become: true
  apt:
    update_cache: true
    pkg:
      - xsel
      - gnome-tweaks
      - libtool-bin
      - cmake
      - unzip
      - neovim
      - syncthing
      - tmux
      - silversearcher-ag
      - texlive-full
      - j4-dmenu-desktop
      # - virtualbox
      - zeal
      # - vlc
      - keepassxc
      - maildir-utils
      - offlineimap
      - net-tools
      - zsh
      - graphviz
      - git-crypt
      - wireshark
      - ncdu
      - inotify-tools
      - hsetroot
      - pandoc
      - texlive-latex-base
      - texlive-fonts-recommended
      - texlive-extra-utils
      - texlive-latex-extra
      - ranger
      - clamav
      - clamtk
      - emacs
      - adb
      - obs-studio
      - libpq-dev
      - redis-tools
      - rsync
      - ffmpeg
      - python3-pip
      - mosh
      - encfs

- name: Install a .deb package from the internet.
  become: yes
  apt:
    deb: "{{ item.url }}"
  with_items:
    - { url: "https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb" }
    - { url: "https://prerelease.keybase.io/keybase_amd64.deb" }
    - { url: "https://zoom.us/client/5.15.11.7239/zoom_amd64.deb" }

# - name: Install packages by snap
#   become: true
#   snap:
#     name:
#       - languagetool
#       - ripgrep
#       - ngrok
#       - grafana
#       - lefthook
#       - slack
#       - k9s
#       - kubectl
#       - heroku
#     classic: yes

- name: Install viddy
  shell: "go install github.com/sachaos/viddy@latest"
