k9s:
  refreshRate: 2
  logBufferSize: 1000
  logRequestSize: 200
  currentContext: do-fra1-tg-storefront
  currentCluster: do-fra1-tg-storefront
  clusters:
    do-fra1-tg-storefront:
      namespace:
        active: tg-ecwid-prod
        favorites:
        - tg-ecwid-prod
        - default
      view:
        active: po
