- name: Clone doom emacs
  git:
    repo: 'https://github.com/doomemacs/doomemacs'
    dest: '~/.config/emacs'
    depth: 1

- name: Find all files in files
  delegate_to: localhost
  find:
    paths: '{{ role_path }}/files'
    hidden: true
    recurse: yes
  register: find

- name: Ensure dir
  file:
    state: directory
    path: "{{ item.src }}"
  with_items:
    - { src: '~/.config/doom' }

- name: Create symlinks
  file:
    src: "{{ item.path }}"
    dest: "~/.config/doom/{{ item.path | relpath(role_path + '/files') }}"
    state: link
    force: yes
  with_items: "{{ find.files }}"

- name: Install doom emacs
  shell: '~/.config/emacs/bin/doom install --force'
